version: '2'

services:
  server:
    image: nikaple/iw-nikaple-server
    ports:
      - "3738:3738/tcp"
      - "3738:3738/udp"
    links:
      - mongo
    depends_on:
      - mongo
      
  mongo:
    image: registry.docker-cn.com/library/mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"