version: '2'

services:
  iw-nikaple-server:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3738:3738/tcp"
      - "3738:3738/udp"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: registry.docker-cn.com/library/mongo